name: update-docs
on: [push]
jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - run: python --version
      - run: python -m pip install -r requirements.txt
