name: update-docs
on: 
  push:
  workflow_dispatch:
  schedule: 
    - cron: '0 5 * * *'
permissions:
  contents: write
jobs:
  extracted-tables-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Run extracted tables python script
        run: python python/extracted_table_docs.py
      - name: Check for modified files
        id: git-check
        run: |
          result=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
          echo "modified=$result" > "$GITHUB_OUTPUT"
      - name: Print result of modification check
        env:
          OUTPUT: ${{ steps.git-check.outputs.modified }}
        run: echo "Git Check Output - $OUTPUT"
      - name: Commit output if changed
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Angela Zoss via GitHub Actions'
          git config --global user.email 'amzoss@users.noreply.github.com'
          git add -A
          git commit -m "[automated commit] update output from extracted_table_docs.py"
          git push
